version: '3.3'

services: 
    watering_db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
            - 3306:3306
        environment:
            MYSQL_DATABASE: watering_system
            MYSQL_ROOT_PASSWORD: watering
            MYSQL_USER: watering
            MYSQL_PASSWORD: watering
