spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/watering_system?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: watering
    password: watering
    dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  token: dkjJGSYt7gb476bZJHDG76tg42uyhb5437kLxdh9827,.ds.okpo78645KsjdSgt43[ery834bgds]
  timeout: 3600
  refresh-timeout: 604800
mqtt:
  broker-url: tcp://52.179.81.237:1883
  client-id: watering
  publish-topic: T_1
  subscribe-topic: T_2
  username: username
  password: password
