spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/watering_system?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: watering
    password: watering
jwt:
  token: dkjJGSYt7gb476bZJHDG76tg42uyhb5437kLxdh9827,.ds.okpo78645KsjdSgt43[ery834bgds]
  timeout: 3600
  refresh-timeout: 604800
mqtt:
  broker-url: ws://13.76.221.132:8083
  client-id: watering
  topic-filter: T_2, T_3

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa

#mqtt:
#  broker-url: tcp://52.179.81.237:1883
#  client-id: watering
#  topic-filter: T
