spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/watering_system?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: watering
    password: watering
    dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  token: dkjJGSYt7gb476bZJHDG76tg42uyhb5437kLxdh9827,.ds.okpo78645KsjdSgt43[ery834bgds]
  timeout: 3600
  refresh-timeout: 604800
mqtt:
  broker-url: tcp://168.63.137.21:1883
  client-id: watering_coder_team
  publish-topic: Topic/Speaker
  subscribe-topic: Topic/#
  username: BKvm2
  password: Hcmut_CSE_2020
